#!/bin/bash
if [ $# -eq 0 ]
then
        echo "Il n'y a pas d'arguments"
        exit 1
else
        if [ -d $1 ]
        then
                if [[ $2 =~ ^[0-9]+$ ]]
                then
                        if [ -f $3 ]
                        then
                                echo "Extract in progress"
                        else
                                echo "L'archive sélectionné n'existe pas"
                        fi
                else
                        echo "Le numéro de port sélectionné n'est pas correct ou n'est pas un numéro"
                        exit 1
                fi
        else
                echo "Le serveur sélectionné n'existe pas"
                exit 1
        fi
fi

