#!/bin/bash
if [ $# -eq 0 ]
then
        echo "Il n'y a pas d'arguments"
else
        if [ -f $1  ]
	then
		debut_header=$(head -n 1 $1 | cut -d: -f1)
		debut_body=$(head -n 1 $1 | cut -d: -f2)
		nb_lignes=$(wc -l $1 | cut -d' ' -f1)
		#selection du header
		touch temp
		#echo "temp à été créé"
		touch header
		#echo "header à été créé"
		head -n $(($debut_body-1)) $1 > temp
		tail -n $(($debut_body-$debut_header)) temp > header
		#selection du body
		touch body
		#echo "body à été créé"
		tail -n $(($nb_lignes-$debut_body+1)) $1 > temp
		cat temp > body
		rm temp
	else
		echo "L'archive sélectionnée n'existe pas"
	fi
fi

