#!/bin/bash
testrights()
{
	nb=0
	#echo "test : $1"
	if [[ $(echo $1 | grep "r") ]]
	then
		((nb=$nb+4))
		#echo "+4"
	fi
	if [[ $(echo $1 | grep "w") ]]
	then
		((nb=$nb+2))
		#echo "+2"
	fi
	if [[ $(echo $1 | grep "x") ]]
	then
		((nb=$nb+1))
		#echo "+1"
	fi
	echo $nb
}
if [ $# -eq 0 ]
then
	echo "Il n'y a pas d'argument"
else
	right=$1
	echo $line
	nbc=$(echo -n $right | wc -c)
	if [ $nbc -eq 9 ]
	then
		gp1=$(echo $right | sed 's/\(^...\).*/\1/')
		#echo "gp1 = $gp1"
		vgp1=$(testrights $gp1)
		#echo $vgp1

		gp2=$(echo $right | sed 's/^...\(...\).*/\1/')
		#echo "gp2 = $gp2"
		vgp2=$(testrights $gp2)
		#echo $vgp2

		gp3=$(echo $right | sed 's/.*\(...\)$/\1/')
		#echo "gp3 = $gp3"
		vgp3=$(testrights $gp3)
		#echo $vgp3

		((rights=$vgp1*100+$vgp2*10+$vgp3))
		echo $rights
	else
		echo "Les droits ne sont pas enregistrés correctement"
		echo "Veuillez les modifier au bon format"
	fi
fi